"use client";

import { useActionState, useId, useState } from "react";
import { Button, Container, Section, SectionHeading } from "@/components/ui";
import { askDemoAction } from "@/lib/demo/actions";
import type { AskAnswer, AskDemoResult, PassageHit } from "@/lib/demo/types";
import type { DemoStatus } from "@/lib/demo/status";

const RETRIEVER_LABEL = {
  lexical: "BM25 keyword scoring",
  vector: "Embedding similarity",
} as const;

const SUGGESTIONS = [
  "How do you stop an automation from sending the same email twice?",
  "What happens when retrieval finds no relevant context?",
  "Where does a human approve something before it is sent?",
];

function StatusRow({
  status,
  answer,
}: {
  status: DemoStatus;
  answer: AskAnswer;
}) {
  const items: { label: string; value: string }[] = [
    {
      label: "Retriever",
      value: RETRIEVER_LABEL[answer.retriever],
    },
    {
      label: "Index",
      value: `${status.passageCount} passages from this site`,
    },
    {
      label: "Answer",
      value: answer.saved
        ? "Saved example"
        : answer.cached
          ? "Cached — no model call"
          : `Generated by ${answer.model}`,
    },
  ];

  return (
    <dl className="grid grid-cols-1 gap-px overflow-hidden rounded-lg border border-outline-variant bg-outline-variant sm:grid-cols-3">
      {items.map((item) => (
        <div key={item.label} className="bg-surface-container px-4 py-3">
          <dt className="font-label text-on-surface-faint">{item.label}</dt>
          <dd className="mt-1 text-body-sm text-on-surface">{item.value}</dd>
        </div>
      ))}
    </dl>
  );
}

function PassageCard({ passage, position }: { passage: PassageHit; position: number }) {
  return (
    <li className="rounded-lg border border-outline-variant bg-surface-container px-4 py-4">
      <div className="flex items-baseline justify-between gap-3">
        <p className="font-label text-on-surface-faint">
          <span className="tabular">[{position}]</span> {passage.section}
        </p>
        <p className="font-mono text-[0.6875rem] text-on-surface-faint">
          <span className="tabular">{passage.score.toFixed(2)}</span>
        </p>
      </div>

      <div
        className="mt-2 h-px w-full bg-outline-variant"
        aria-hidden
      >
        <div
          className="h-px bg-accent transition-[width] duration-300 ease-out motion-reduce:transition-none"
          style={{ width: `${Math.max(4, Math.round(passage.score * 100))}%` }}
        />
      </div>

      <p className="mt-3 text-body-sm text-on-surface-variant">{passage.text}</p>

      <a
        href={passage.sourceHref}
        className="link-underline mt-3 inline-block text-body-sm text-on-surface-variant hover:text-accent"
      >
        {passage.sourceTitle}
      </a>
    </li>
  );
}

export function AskDemoSection({ status }: { status: DemoStatus }) {
  const [state, formAction, pending] = useActionState<AskDemoResult | null, FormData>(
    askDemoAction,
    null,
  );
  const [question, setQuestion] = useState(
    status.mode === "live" ? "" : status.example.question,
  );

  const fieldId = useId();
  const errorId = useId();

  const answer: AskAnswer = state?.ok ? state.result : status.example;
  const isExample = answer.saved;
  const error = state && !state.ok ? state.error : null;

  return (
    <Section id="ask" divider>
      <Container>
        <SectionHeading
          eyebrow="Try it"
          title="Ask my case studies"
          description="A retrieval-augmented answer built from this site's own content: your question is scored against the case-study passages, and the model may only answer from the passages it gets back."
        />

        <div className="mt-12 grid grid-cols-1 gap-8 lg:grid-cols-12">
          <div className="lg:col-span-7">
            <form action={formAction} className="panel panel-depth px-5 py-5 md:px-6">
              <label
                htmlFor={fieldId}
                className="font-label block text-on-surface-faint"
              >
                Your question
              </label>

              <div className="mt-3 flex flex-col gap-3 sm:flex-row">
                <input
                  id={fieldId}
                  name="question"
                  type="text"
                  value={question}
                  onChange={(event) => setQuestion(event.target.value)}
                  maxLength={status.maxQuestionLength}
                  disabled={status.mode !== "live" || pending}
                  placeholder="What reliability controls do your workflows have?"
                  aria-describedby={error ? errorId : undefined}
                  className="w-full rounded-md border border-outline-variant bg-surface-low px-4 py-3 text-on-surface placeholder:text-on-surface-variant/60 transition-colors focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent disabled:opacity-60"
                />
                <div className="shrink-0">
                  <Button
                    type="submit"
                    variant="accent"
                    size="lg"
                    disabled={status.mode !== "live" || pending}
                    className="w-full sm:w-auto"
                  >
                    {pending ? "Retrieving…" : "Ask"}
                  </Button>
                </div>
              </div>

              {status.mode === "live" ? (
                <>
                  <ul className="mt-4 flex flex-wrap gap-2">
                    {SUGGESTIONS.map((suggestion) => (
                      <li key={suggestion}>
                        <button
                          type="button"
                          onClick={() => setQuestion(suggestion)}
                          disabled={pending}
                          className="rounded-full border border-outline-variant bg-surface-high px-3 py-1 text-left font-mono text-[0.6875rem] text-on-surface-variant transition-colors duration-200 hover:border-outline-strong hover:text-on-surface focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-accent disabled:opacity-60"
                        >
                          {suggestion}
                        </button>
                      </li>
                    ))}
                  </ul>
                  <p className="mt-4 text-body-sm text-on-surface-faint">
                    Limited to {status.rateLimit} questions per {status.rateWindowMinutes}{" "}
                    minutes, and to a daily total — the answer step calls a paid model.
                  </p>
                </>
              ) : (
                <p className="mt-4 text-body-sm text-on-surface-faint">
                  The answer step is switched off on this deployment, so the box is
                  disabled and a saved example is shown instead. The retrieval below is
                  still computed live from the passage index.
                </p>
              )}
            </form>

            <div aria-live="polite" aria-busy={pending}>
              {error ? (
                <p
                  id={errorId}
                  role="alert"
                  className="mt-4 rounded-lg border border-outline-variant bg-surface-container px-4 py-3 text-body-sm text-on-surface-variant"
                >
                  {error}
                </p>
              ) : null}

              <div className="mt-6">
                <StatusRow status={status} answer={answer} />
              </div>

              <div className="mt-4 rounded-lg border border-outline-variant bg-surface-container px-5 py-5">
                <p className="font-label text-on-surface-faint">
                  {isExample ? "Saved example — question and answer" : "Answer"}
                </p>
                <p className="mt-3 text-body-lg text-on-surface">
                  {answer.question}
                </p>
                <p className="mt-4 text-body-md text-on-surface-variant">
                  {answer.answer}
                </p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-5">
            <p className="font-label text-on-surface-faint">
              Retrieved passages{" "}
              <span className="tabular">
                ({answer.passages.length}/{status.passageCount})
              </span>
            </p>
            <p className="mt-2 text-body-sm text-on-surface-faint">
              Scored by {RETRIEVER_LABEL[answer.retriever].toLowerCase()}, relative to
              the top match. These are the only passages the answer may use.
            </p>
            <ol className="mt-4 space-y-3">
              {answer.passages.map((passage, index) => (
                <PassageCard
                  key={passage.id}
                  passage={passage}
                  position={index + 1}
                />
              ))}
            </ol>
          </div>
        </div>
      </Container>
    </Section>
  );
}
